### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by trtm** [jgraving/vaesne#1]
This work looks really interesting for my current project.
When do you plan to publish the code? Perhaps even a package on pypi.org 😉

All the best!

**Comment by lefnire** [comment]
Likewise, very interested to try this out.

**Comment by diogoseca** [comment]
Bump

**Comment by antortjim** [comment]
Very interested here too! :smile:

**Comment by davnovak** [comment]
Also very interested.

**Comment by trtm** [comment]
Yo, that's no exactly a year since my initial request. Any updates on the code release part? @jgraving

**Comment by DanBenHa** [comment]
There's been a pre-release on pypi: https://pypi.org/project/vaesne Unfortunately, this looks pretty abandoned and I would be very cautious about the results.

**Comment by jgraving** [comment]
Hi @trtm (and others), the manuscript is in revision, and I am refactoring the code. The version @DanBenHa pointed to is a placeholder on pypi and is not fully functional. 

After posting the pre-print I had to finish my PhD, move apartments, and start a new job, so this is the reason for the long delay. I am actively working on it now and plan to release the code publicly by early fall.
